version: '3.7'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq

  entry-exit-service:
    build:
      context: ./entry-exit-service
    ports:
      - '3001:3000'
    depends_on:
      - rabbitmq
      - db_entry_exit
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_entry_exit/entry_exit_service"

  payment-service:
    build:
      context: ./payment-service
    ports:
      - '3002:3000'
    depends_on:
      - rabbitmq
      - db_payment
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_payment/payment_service"

  parking-spot-service:
    build:
      context: ./parking-spot-service
    ports:
      - '3003:3000'
    depends_on:
      - rabbitmq
      - db_parking
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_parking/parking_spot_service"

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'

  db_entry_exit:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: entry_exit_service
    ports:
      - "5432:5432"

  db_payment:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_service
    ports:
      - "5433:5432"

  db_parking:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking_spot_service
    ports:
      - "5434:5432"
