version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PORT: 5672  # Define a porta do RabbitMQ como uma variável de ambiente

  entry-exit-service:
    build:
      context: ./entry-exit-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "file:./dev.db"  # SQLite
      RABBITMQ_URL: "amqp://rabbitmq:${RABBITMQ_PORT}"
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "file:./dev.db"  # SQLite
      RABBITMQ_URL: "amqp://rabbitmq:${RABBITMQ_PORT}"
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"

  parking-spot-service:
    build:
      context: ./parking-spot-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "file:./dev.db"  # SQLite
      RABBITMQ_URL: "amqp://rabbitmq:${RABBITMQ_PORT}"
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - entry-exit-service
      - payment-service
      - parking-spot-service
      - rabbitmq
    ports:
      - "3003:3003"
