version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"  # RabbitMQ
      - "15672:15672"  # RabbitMQ Management UI
    networks:
      - nest-microservices-network

  postgres_entry_exit:
    image: postgres:latest
    environment:
      POSTGRES_DB: entry_exit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # PostgreSQL
    networks:
      - nest-microservices-network

  postgres_parking_spot:
    image: postgres:latest
    environment:
      POSTGRES_DB: parking_spot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # PostgreSQL
    networks:
      - nest-microservices-network

  postgres_payment:
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # PostgreSQL
    networks:
      - nest-microservices-network

  entry-exit-service:
    build:
      context: ./entry-exit-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_URL=postgresql://postgres:postgres@postgres_entry_exit:5432/entry_exit_db
    depends_on:
      - rabbitmq
      - postgres_entry_exit
    networks:
      - nest-microservices-network

  parking-spot-service:
    build:
      context: ./parking-spot-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_URL=postgresql://postgres:postgres@postgres_parking_spot:5432/parking_spot_db
    depends_on:
      - rabbitmq
      - postgres_parking_spot
    networks:
      - nest-microservices-network

  payment-service:
    build:
      context: ./payment-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_URL=postgresql://postgres:postgres@postgres_payment:5432/payment_db
    depends_on:
      - rabbitmq
      - postgres_payment
    networks:
      - nest-microservices-network

networks:
  nest-microservices-network:
    driver: bridge
