version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db_entry_exit:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: entry_exit_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  db_payment:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: payment_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"

  db_parking:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: parking_spot_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5434"

  entry-exit-service:
    build:
      context: ./entry-exit-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_entry_exit:5432/entry_exit_service"
    depends_on:
      - db_entry_exit
      - rabbitmq

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_payment:5433/payment_service"
    depends_on:
      - db_payment
      - rabbitmq

  parking-spot-service:
    build:
      context: ./parking-spot-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db_parking:5434/parking_spot_service"
    depends_on:
      - db_parking
      - rabbitmq

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - entry-exit-service
      - payment-service
      - parking-spot-service
