# kubernetes/postgres-payment/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: postgres-payment-service
spec:
  selector:
    app: postgres-payment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
