# kubernetes/postgres-parking-spot/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: postgres-parking-spot-service
spec:
  selector:
    app: postgres-parking-spot
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
